# Generated by Django 4.1 on 2022-09-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangwatchlist',
            old_name='Watched',
            new_name='watched',
        ),
        migrations.AlterField(
            model_name='barangwatchlist',
            name='rating',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='barangwatchlist',
            name='release_date',
            field=models.TextField(),
        ),
    ]
